#!/usr/bin/env sh
# emit-runtime-env.sh — write the compose-level runtime env file.
#
# Context: some containers in docker-compose.yml are upstream images
# (elasticsearch, neo4j) that don't know how to resolve op(...) refs
# themselves. Their passwords live in 1Password, but compose's env_file:
# directive wants a plain key=value file on the host filesystem.
#
# This script runs inside the `secrets-init` compose service (same image
# as honeybot, so it has the op CLI and the service account token). It
# reads the handful of values those upstream containers need and writes
# them to a bind-mounted path on the host (/repo/.env.runtime).
#
# The resulting file is treated exactly like op.env: gitignored,
# dockerignored, chmod 600. It is regenerated from scratch on every
# compose run, so rotating a value in 1Password + `docker compose up -d`
# is the rotation workflow.
#
# Scope is deliberately tight: ONLY the values that compose needs to
# interpolate into a non-Varlock-aware container. Bot-level secrets that
# get consumed by the honeybot container itself stay resolved via
# varlock inside the container — they do NOT go in this file.
#
# Usage: emit-runtime-env.sh <output-path>
#   Typically invoked as: emit-runtime-env.sh /repo/.env.runtime

set -eu

OUT="${1:-/repo/.env.runtime}"

log() { printf 'emit-runtime-env: %s\n' "$*"; }
die() { printf 'emit-runtime-env: FATAL: %s\n' "$*" >&2; exit 1; }

[ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] || \
  die "OP_SERVICE_ACCOUNT_TOKEN not set"

command -v op >/dev/null 2>&1 || die "op CLI missing"

# Fresh write on every run — never append. If the file exists from a
# previous run, overwrite it.
OUT_DIR="$(dirname "$OUT")"
[ -d "$OUT_DIR" ] || die "output directory $OUT_DIR does not exist (bind mount missing?)"

TMP="${OUT}.tmp"

# Values we emit. If 1Password is missing any of these, fail closed —
# the seeder should have populated them before this script runs.
read_or_die() {
  ref="$1"
  val="$(op read "$ref" 2>/dev/null || true)"
  [ -n "$val" ] || die "empty/missing: $ref (did seed-vault.sh run?)"
  printf '%s' "$val"
}

ELASTIC_PASSWORD="$(read_or_die 'op://Honeybot/Elasticsearch/password')"
NEO4J_AUTH="$(read_or_die 'op://Honeybot/Neo4j/auth')"

# Write atomically so partial writes can't confuse compose.
umask 077
{
  printf '# Generated by scripts/emit-runtime-env.sh. Do not edit by hand.\n'
  printf '# Regenerated on every compose up via the secrets-init service.\n'
  printf 'ELASTIC_PASSWORD=%s\n' "$ELASTIC_PASSWORD"
  printf 'NEO4J_AUTH=%s\n' "$NEO4J_AUTH"
} > "$TMP"
mv "$TMP" "$OUT"
chmod 600 "$OUT"

log "wrote $OUT (mode 600)"
