#!/usr/bin/env sh
# emit-runtime-env.sh — write the compose-level runtime env file.
#
# Context: some containers in docker-compose.yml are upstream images
# (elasticsearch, neo4j) that don't know how to resolve op(...) refs
# themselves. Their passwords live in 1Password, but compose's env_file:
# directive wants a plain key=value file on the host filesystem.
#
# This script runs inside the `secrets-init` compose service (same image
# as honeybot, so it has the op CLI and the service account token). It
# reads the handful of values those upstream containers need and writes
# them to a bind-mounted path on the host (/repo/.env.runtime).
#
# The resulting file is treated exactly like op.env: gitignored,
# dockerignored, chmod 600. It is regenerated from scratch on every
# compose run, so rotating a value in 1Password + `docker compose up -d`
# is the rotation workflow.
#
# Scope is deliberately tight: ONLY the values that compose needs to
# interpolate into a non-Varlock-aware container. Bot-level secrets that
# get consumed by the honeybot container itself stay resolved via
# varlock inside the container — they do NOT go in this file.
#
# Usage: emit-runtime-env.sh <output-path>
#   Typically invoked as: emit-runtime-env.sh /repo/.env.runtime

set -eu

OUT="${1:-/repo/.env.runtime}"

log()  { printf 'emit-runtime-env: %s\n' "$*"; }
warn() { printf 'emit-runtime-env: WARN: %s\n' "$*" >&2; }
die()  { printf 'emit-runtime-env: FATAL: %s\n' "$*" >&2; exit 1; }

# Catastrophic conditions still abort — without these we couldn't read
# anything, full stop.
[ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] || \
  die "OP_SERVICE_ACCOUNT_TOKEN not set"
command -v op >/dev/null 2>&1 || die "op CLI missing"

OUT_DIR="$(dirname "$OUT")"
[ -d "$OUT_DIR" ] || die "output directory $OUT_DIR does not exist (bind mount missing?)"

TMP="${OUT}.tmp"

# Per-secret resolution is BEST-EFFORT, not fail-closed. Missing or empty
# values are logged as warnings and emitted as empty assignments, so the
# downstream service can decide how to handle the gap on its own.
#
# Rationale: a single missing secret should localize damage to the one
# subsystem that needs it (e.g. Elasticsearch fails to start), not bring
# down secrets-init and cascade into honeybot/hermes, which doesn't even
# need ES/Neo4j to come up. The previous fail-closed behavior took the
# whole stack down whenever a vault item was empty or shadowed by a
# duplicate.
#
# Track whether anything was missing so we can summarize at the end.
MISSING_COUNT=0
read_or_warn() {
  ref="$1"
  val="$(op read "$ref" 2>/dev/null || true)"
  if [ -z "$val" ]; then
    warn "empty/missing: $ref (downstream service will not start)"
    MISSING_COUNT=$((MISSING_COUNT + 1))
  fi
  printf '%s' "$val"
}

# read_or_silent — same as read_or_warn but for OPTIONAL values where
# missing is fine (e.g. a notification webhook the operator may not have
# set up yet). No warn, no MISSING_COUNT bump.
read_or_silent() {
  ref="$1"
  op read "$ref" 2>/dev/null || true
}

ELASTIC_PASSWORD="$(read_or_warn 'op://Honeybot/Elasticsearch/password')"
NEO4J_AUTH="$(read_or_warn 'op://Honeybot/Neo4j/auth')"

# Write atomically so partial writes can't confuse compose. Empty values
# are emitted as `KEY=` so compose's env_file parser doesn't choke; the
# downstream container sees an empty env var and fails its own startup
# in isolation.
umask 077
{
  printf '# Generated by scripts/emit-runtime-env.sh. Do not edit by hand.\n'
  printf '# Regenerated on every compose up via the secrets-init service.\n'
  printf 'ELASTIC_PASSWORD=%s\n' "$ELASTIC_PASSWORD"
  printf 'NEO4J_AUTH=%s\n' "$NEO4J_AUTH"
} > "$TMP"
mv "$TMP" "$OUT"
chmod 600 "$OUT"

if [ "$MISSING_COUNT" -gt 0 ]; then
  log "wrote $OUT (mode 600) with $MISSING_COUNT missing value(s) — see WARN lines above"
else
  log "wrote $OUT (mode 600)"
fi
# Always exit 0: secrets-init's job is to do its best and let downstream
# services succeed/fail independently.
exit 0
